### ISSUE TITLE
Skipping compressed file as an option?

### ISSUE THREAD

**Issue by nickjj** [zarqman/propshaft-compressor#1]
Hi,

I understand why you skipped compressing jpgs and other files but the advantage of pre-compress is so your web server doesn't have to. If jpgs and other images aren't gzipped then nginx or your web server will be gzipping them on the fly which is the action we're trying to prevent.

Maybe that file type skip list could be made a configuration option which defaults to skipping nothing? This way it will pre-compress everything but if you want to omit files as an end user you can.

**Comment by zarqman** [comment]
I'm certainly open to making it configurable. 😄 

Most Nginx configurations I've seen use an include-list of mime-types to compress and, regarding images, usually only include `image/svg+xml` (or skip image/* entirely). It's usually similar for other webservers that I've seen, but I certainly haven't done an exhaustive survey or anything.

How do you usually configure Nginx's gzip module?

**Comment by nickjj** [comment]
That's a good point. It's been a while since I looked at my nginx config. Maybe this gem being configurable isn't needed then?

At the moment I have nginx configured to only gzip these mime types. This list probably needs to be re-visited since I haven't touched it in like 10 years:

```
  text/richtext
  text/plain
  text/css
  text/x-script
  text/x-component
  text/x-java-source
  text/x-markdown
  application/javascript
  application/x-javascript
  text/javascript
  text/js
  image/x-icon
  application/x-perl
  application/x-httpd-cgi
  text/xml
  text/html
  application/xml
  application/xml+rss
  application/json
  multipart/bag
  multipart/mixed
  application/xhtml+xml
  font/ttf
  font/otf
  font/x-woff
  image/svg+xml
  application/vnd.ms-fontobject
  application/ttf
  application/x-ttf
  application/otf
  application/x-otf
  application/truetype
  application/opentype
  application/x-opentype
  application/font-woff
  application/eot
  application/font
  application/font-sfnt
  application/wasm
```

**Comment by zarqman** [comment]
My last nginx config is shorter (fewer font types as I dropped eot,ttf,otf years ago), but about the same idea (and probably nearly as old!)

I don't use a lot of jpg's, but a limited test here of larger, photo-based .jpg's saves 3% with brotli & gzip, and gains(!) 1% with zstd. Would need more testing to see how that works on smaller files though.

Several woff's are ±1%. woff2's are all break-even to slight increases. (Both of these are compressed internally, so I'd expect that.)

You should be able to test compressing everything by adding `Propshaft::Compressor::SKIP_EXTS.clear` to `application.rb` (just as a test; we can still explore a proper config option if appropriate).

**Comment by nickjj** [comment]
Thanks, do you want to close this?

I'll leave it up to you because I think you provided a few ways to either make this a non-issue or override that array (yay for Ruby for making this so easy).

**Comment by zarqman** [comment]
Cool, let's close it for now. Can always revisit if needed.
